name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  actions: write

jobs:
  cleanup:
    name: Delete Old Runs
    runs-on: ubuntu-latest

    steps:
      - name: Delete Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7   # Keep only the last 7 days of runs
          keep_minimum_runs: 5 # Always keep at least the last 5 runs
