name: Build Unity Project

#on: [push, pull_request]

on:
  # Manual trigger: This allows the workflow to be triggered manually from GitHub UI
  workflow_dispatch:

  # Scheduled trigger: This runs the workflow on a schedule (daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write
  packages: write
  
jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.build_project.outputs.buildVersion }}
      output2: ${{ env.COMMIT_ID }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL. 
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if there was a recent push
        id: check_push
        run: |
          # Get the timestamp of the last commit
          last_push=$(git log -1 --format=%ct)
          current_time=$(date +%s)
          time_diff=$((current_time - last_push))
          
          # Define a threshold (e.g., 12 hours = 43200 seconds)
          if [ $time_diff -gt 43200 ]; then
            echo "No recent push. Skipping scheduled job."
            exit 1  # Fail the step to stop further execution
          fi
          echo "Recent push detected, continuing with the scheduled job."

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-

      # - name: Extract date
      #   id: extract_date
      #   run: |
      #     COMMIT_DATE=$(date +'%Y.%m.%d')
      #     echo "COMMIT_DATE=${COMMIT_DATE}" >> $GITHUB_ENV
      #     echo "$COMMIT_DATE"

      - name: Get commit message header
        id: get_commit_message
        run: |
          COMMIT_ID=$(git log -1 --pretty=%h)
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
          echo "$COMMIT_ID"
        
      # Build
      - name: Build project
        id: build_project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          versioning: Semantic

      - name: Edit index.html
        id: edit_index_html
        run: |
            set -x
            export INDEX=$(find ./ -name index.html)
            sudo sed -i 's/width=960 height=600/width=auto height=auto/' $INDEX
            sudo sed -i 's/style="width: 960px; height: 600px;/style="width: 100%; height: 100%;/' $INDEX
            sudo sed -i 's/});/});\n      var WAMScore = 0; var getWAMScore = msg => (WAMScore = parseInt(msg), console.log("Win:" + WAMScore));/' $INDEX
      
      # Output
      - name: Upload build artifacts
        id: upload_build_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}_${{ steps.build_project.outputs.buildVersion }}_${{ env.COMMIT_ID }}
          path: build/${{ matrix.targetPlatform }}
        
  release:
    name: Release project
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL. 
    steps:   
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts/${{ matrix.targetPlatform }}
  
      - name: Zipping Downloaded Build
        env:
          BUILD_VERSION: ${{ needs.build.outputs.output1 }}
          BUILD_COMMIT_ID: ${{ needs.build.outputs.output2 }}
        run: |
          zip -r build-artifacts/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}.zip -9 build-artifacts/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}/${{ matrix.targetPlatform}}/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_VERSION: ${{ needs.build.outputs.output1 }}
          BUILD_COMMIT_ID: ${{ needs.build.outputs.output2 }}
        with:
          name: WhackAMole_${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}
          tag_name: ${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}
          files: |
            build-artifacts/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}.zip
